# Experiment No. 1
## Data Pre-processing on a Raw Dataset

### Aim

To perform data pre-processing on a given raw dataset to improve data quality for further analysis.

### Step 1: Import the Libraries

The required Python libraries are imported for numerical operations, data handling, data visualization, and statistical visualization.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Step 2: Import the Dataset

The Employee dataset is loaded using Pandas. The dataset contains information such as Company, Age, Salary, Place, Country, and Gender.

In [2]:
df = pd.read_csv('Employee.csv')

df.shape

(148, 6)

This displays the complete Employee dataset so that we can initially examine its rows and columns.

In [3]:
df

     Company   Age  Salary     Place Country  Gender
0        TCS  20.0     NaN   Chennai   India       0
1    Infosys  30.0     NaN    Mumbai   India       0
2        TCS  35.0  2300.0  Calcutta   India       0
3    Infosys  40.0  3000.0     Delhi   India       0
4        TCS  23.0  4000.0    Mumbai   India       0
..       ...   ...     ...       ...     ...     ...
143      TCS  33.0  9024.0  Calcutta   India       1
144  Infosys  22.0  8787.0  Calcutta   India       1
145  Infosys  44.0  4034.0     Delhi   India       1
146      TCS  33.0  5034.0    Mumbai   India       1
147  Infosys  22.0  8202.0    Cochin   India       0

[148 rows x 6 columns]

### Step 3: Check for Duplicate Records

The `duplicated()` function identifies duplicate rows in the Employee dataset. The `sum()` function gives the total number of duplicate rows.

In [4]:
df.duplicated().sum()

np.int64(4)

The `drop_duplicates()` function removes duplicate records from the dataset. The `inplace=True` option directly updates the existing DataFrame.

In [5]:
df.drop_duplicates(inplace=True)

df.shape

(144, 6)

After removing duplicate rows, the index may contain gaps. The index is reset so that the rows have continuous numbering.

In [6]:
df.reset_index(inplace=True)

df.drop('index', axis=1, inplace=True)

df

             Company   Age  Salary     Place Country  Gender
0                TCS  20.0     NaN   Chennai   India       0
1            Infosys  30.0     NaN    Mumbai   India       0
2                TCS  35.0  2300.0  Calcutta   India       0
3            Infosys  40.0  3000.0     Delhi   India       0
4                TCS  23.0  4000.0    Mumbai   India       0
..               ...   ...     ...       ...     ...     ...
139  Infosys Pvt Lmt  22.0  8202.0    Mumbai   India       0
140              TCS  33.0  9024.0  Calcutta   India       1
141          Infosys  44.0  4034.0     Delhi   India       1
142              TCS  33.0  5034.0    Mumbai   India       1
143          Infosys  22.0  8202.0    Cochin   India       0

[144 rows x 6 columns]

The `head()` function displays the first five rows of the dataset for a quick inspection.

In [7]:
df.head(5)

   Company   Age  Salary     Place Country  Gender
0      TCS  20.0     NaN   Chennai   India       0
1  Infosys  30.0     NaN    Mumbai   India       0
2      TCS  35.0  2300.0  Calcutta   India       0
3  Infosys  40.0  3000.0     Delhi   India       0
4      TCS  23.0  4000.0    Mumbai   India       0

The `info()` function displays information about the dataset, including the number of entries, column names, data types, and non-null values.

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Company  136 non-null    str
 1   Age      127 non-null    float64
 2   Salary   121 non-null    float64
 3   Place    130 non-null    str
 4   Country  144 non-null    str
 5   Gender   144 non-null    int64
dtypes: float64(2), int64(1), str(3)
memory usage: 6.9 KB

The `isna().sum()` function calculates the number of missing values present in each column.

In [9]:
df.isna().sum()

Company     8
Age        17
Salary     23
Place      14
Country     0
Gender      0
dtype: int64

The `columns` attribute displays all column names present in the Employee dataset.

In [10]:
df.columns

Index(['Company', 'Age', 'Salary', 'Place', 'Country', 'Gender'], dtype='str')

The `nunique()` function calculates the number of unique values present in each column.

In [11]:
unique = df.nunique()

unique

Company     6
Age        29
Salary     40
Place      11
Country     1
Gender      2
dtype: int64

The `unique()` function displays all different values present in the Company column. This helps identify inconsistent company names.

In [12]:
df['Company'].unique()

<StringArray>
[                      'TCS',                   'Infosys',
                       'CTS',                         nan,
 'Tata Consultancy Services',                'Congnizant',
           'Infosys Pvt Lmt']
Length: 7, dtype: str

### Step 4: Check Unique Values in Important Columns

The unique values in the Age column are displayed to identify unusual or incorrect entries.

In [13]:
df['Age'].unique()

array([20., 30., 35., 40., 23., nan, 34., 45., 18., 22., 32., 37., 50.,
       21., 46., 36., 26., 41., 24., 25., 43., 19., 38., 51., 31., 44.,
       33., 17.,  0., 54.])

The unique values in the Salary column are displayed to inspect the different salary values present in the dataset.

In [14]:
df['Salary'].unique()

array([  nan, 2300., 3000., 4000., 5000., 6000., 7000., 8000., 9000.,
       1089., 1234., 3030., 3045., 3184., 4824., 5835., 7084., 8943.,
       8345., 9284., 9876., 2034., 7654., 2934., 4034., 5034., 8202.,
       9024., 4345., 6544., 6543., 3234., 4324., 5435., 5555., 8787.,
       3454., 5654., 5009., 5098., 3033.])

The unique values in the Place column are displayed to identify spelling inconsistencies in city names.

In [15]:
df['Place'].unique()

<StringArray>
[   'Chennai',     'Mumbai',   'Calcutta',      'Delhi', 'Podicherry',
     'Cochin',          nan,      'Noida',  'Hyderabad',     'Bhopal',
     'Nagpur',       'Pune']
Length: 12, dtype: str

The incorrect spelling `Podicherry` is repla?ced with `Pondicherry` to maintain consistency in the dataset.

In [16]:
df['Place'].replace('Podicherry', 'Pondicherry', inplace=True)

df['Place'].unique()

C:\Users\rosha\AppData\Local\Temp\ipykernel_20640\1027829238.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Place'].replace('Podicherry', 'Pondicherry', inplace=True)

<StringArray>
[   'Chennai',     'Mumbai',   'Calcutta',      'Delhi', 'Podicherry',
     'Cochin',          nan,      'Noida',  'Hyderabad',     'Bhopal',
     'Nagpur',       'Pune']
Length: 12, dtype: str

The unique values in the Country column are displayed to check whether the country values are consistent.

In [17]:
df['Country'].unique()

<StringArray>
['India']
Length: 1, dtype: str

The unique values in the Gender column are displayed to understand how gender is represented in the dataset.

In [18]:
df['Gender'].unique()

array([0, 1])

### Step 5: Statistical Analysis

The `describe()` function provides statistical information such as count, mean, standard deviation, minimum, maximum, and quartiles for numerical columns.

In [19]:
df.describe()

              Age       Salary      Gender
count  127.000000   121.000000  144.000000
mean    30.527559  5283.471074    0.222222
std     11.114717  2585.373600    0.417191
min      0.000000  1089.000000    0.000000
25%     22.000000  3030.000000    0.000000
50%     33.000000  5000.000000    0.000000
75%     37.500000  8000.000000    0.000000
max     54.000000  9876.000000    1.000000

### Step 6: Outlier Detection

A separate copy of the original Employee dataset is loaded for comparison during the outlier analysis.

In [20]:
df1 = pd.read_csv('Employee.csv')

df1.describe()

              Age       Salary      Gender
count  130.000000   124.000000  148.000000
mean    30.484615  5312.467742    0.222973
std     11.096640  2573.764683    0.417654
min      0.000000  1089.000000    0.000000
25%     22.000000  3030.000000    0.000000
50%     32.500000  5000.000000    0.000000
75%     37.750000  8000.000000    0.000000
max     54.000000  9876.000000    1.000000

The first quartile (Q1) represents the 25th percentile of the Age column.

In [21]:
q1 = df['Age'].quantile(0.25)

q1

np.float64(22.0)

The third quartile (Q3) represents the 75th percentile of the Age column.

In [22]:
q3 = df['Age'].quantile(0.75)

q3

np.float64(37.5)

The Interquartile Range (IQR) is calculated as the difference between Q3 and Q1. It represents the spread of the middle 50% of the data.

In [23]:
iqr = q3 - q1

iqr

np.float64(15.5)

The lower limit is calculated using the IQR rule. Values below this limit can be considered potential outliers.

In [24]:
lower = q1 - 1.5 * iqr

lower

np.float64(-1.25)

The upper limit is calculated using the IQR rule. Values above this limit can be considered potential outliers.

In [25]:
upper = q3 + 1.5 * iqr

upper

np.float64(60.75)

This checks for Age values outside the calculated limits.

In [26]:
df[(df['Age'] < lower) & (df['Age'] > upper)]

Empty DataFrame
Columns: [Company, Age, Salary, Place, Country, Gender]
Index: []

The first quartile (Q1) of the Salary column is calculated to begin the IQR-based outlier detection.

In [27]:
q1 = df['Salary'].quantile(0.25)

q1

np.float64(3030.0)

The third quartile (Q3) of the Salary column is calculated.

In [28]:
q3 = df['Salary'].quantile(0.75)

q3

np.float64(8000.0)

The IQR for Salary is calculated as Q3 minus Q1.

In [29]:
iqr = q3 - q1

iqr

np.float64(4970.0)

The lower limit for Salary is calculated using the IQR rule.

In [30]:
lower = q1 - 1.5 * iqr

lower

np.float64(-4425.0)

The upper limit for Salary is calculated using the IQR rule.

In [31]:
upper = q3 + 1.5 * iqr

upper

np.float64(15455.0)

This checks for Salary values outside the calculated limits.

In [32]:
df[(df['Salary'] < lower) & (df['Salary'] > upper)]

Empty DataFrame
Columns: [Company, Age, Salary, Place, Country, Gender]
Index: []

### Step 7: Handling Missing Values

Before replacing missing values, we check the number of missing values in each column.

In [33]:
df.isnull().sum()

Company     8
Age        17
Salary     23
Place      14
Country     0
Gender      0
dtype: int64

The missing values in the Age column are replaced with the mean age. This allows us to retain the rows instead of deleting them.

In [34]:
df['Age'].fillna(df['Age'].mean(), inplace=True)

df['Age'].isnull().sum()

C:\Users\rosha\AppData\Local\Temp\ipykernel_20640\3237486738.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Age'].fillna(df['Age'].mean(), inplace=True)

np.int64(17)

The missing values in the Salary column are replaced with the mean salary.

In [35]:
df['Salary'].fillna(df['Salary'].mean(), inplace=True)

df['Salary'].isnull().sum()

C:\Users\rosha\AppData\Local\Temp\ipykernel_20640\421364372.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Salary'].fillna(df['Salary'].mean(), inplace=True)

np.int64(23)

The missing values in the Place column are replaced with the mode, which is the most frequently occurring place.

In [36]:
df['Place'].fillna(df['Place'].mode()[0], inplace=True)

df['Place'].isnull().sum()

C:\Users\rosha\AppData\Local\Temp\ipykernel_20640\3823890674.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Place'].fillna(df['Place'].mode()[0], inplace=True)

np.int64(14)

The missing values in the Gender column are replaced using the mode because Gender is a categorical variable.

In [37]:
df['Gender'].fillna(df['Gender'].mode()[0], inplace=True)

df['Gender'].isnull().sum()

C:\Users\rosha\AppData\Local\Temp\ipykernel_20640\3447597443.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Gender'].fillna(df['Gender'].mode()[0], inplace=True)

np.int64(0)

Finally, we check the complete dataset again to confirm whether any missing values remain.

In [38]:
df.isnull().sum()

Company     8
Age        17
Salary     23
Place      14
Country     0
Gender      0
dtype: int64

### Step 8: Encoding Categorical Variables

Before encoding, we check the data types of all columns. Machine learning algorithms generally require numerical input, so categorical columns need to be converted into numerical form.

In [39]:
df.dtypes

Company        str
Age        float64
Salary     float64
Place          str
Country        str
Gender       int64
dtype: object

The Gender column contains categorical values. We convert the categories into numerical values using one-hot encoding.

In [40]:
df = pd.get_dummies(df, columns=['Gender'], dtype=int)

df.head()

   Company   Age  Salary     Place Country  Gender_0  Gender_1
0      TCS  20.0     NaN   Chennai   India         1         0
1  Infosys  30.0     NaN    Mumbai   India         1         0
2      TCS  35.0  2300.0  Calcutta   India         1         0
3  Infosys  40.0  3000.0     Delhi   India         1         0
4      TCS  23.0  4000.0    Mumbai   India         1         0

The Place column is also categorical. One-hot encoding converts each unique place into a separate numerical column.

In [41]:
df = pd.get_dummies(df, columns=['Place'], dtype=int)

df.head()

,Company,Age,Salary,Country,Gender_0,Gender_1,Place_Bhopal,Place_Calcutta,Place_Chennai,Place_Cochin,Place_Delhi,Place_Hyderabad,Place_Mumbai,Place_Nagpur,Place_Noida,Place_Podicherry,Place_Pune
0,TCS,20.0,NaN,India,1,0,0,0,1,0,0,0,0,0,0,0,0
1,Infosys,30.0,NaN,India,1,0,0,0,0,0,0,0,1,0,0,0,0
2,TCS,35.0,2300.0,India,1,0,0,1,0,0,0,0,0,0,0,0,0
3,Infosys,40.0,3000.0,India,1,0,0,0,0,0,1,0,0,0,0,0,0
4,TCS,23.0,4000.0,India,1,0,0,0,0,0,0,0,1,0,0,0,0

The Company column contains categorical company names. One-hot encoding converts these categories into numerical columns.

In [42]:
df = pd.get_dummies(df, columns=['Company'], dtype=int)

df.head()

,Age,Salary,Country,Gender_0,Gender_1,Place_Bhopal,Place_Calcutta,Place_Chennai,Place_Cochin,Place_Delhi,...,Place_Nagpur,Place_Noida,Place_Podicherry,Place_Pune,Company_CTS,Company_Congnizant,Company_Infosys,Company_Infosys Pvt Lmt,Company_TCS,Company_Tata Consultancy Services
0,20.0,NaN,India,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
1,30.0,NaN,India,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2,35.0,2300.0,India,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,40.0,3000.0,India,1,0,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
4,23.0,4000.0,India,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

The Country column is categorical, so it is converted into numerical columns using one-hot encoding.

In [43]:
df = pd.get_dummies(df, columns=['Country'], dtype=int)

df.head()

,Age,Salary,Gender_0,Gender_1,Place_Bhopal,Place_Calcutta,Place_Chennai,Place_Cochin,Place_Delhi,Place_Hyderabad,...,Place_Noida,Place_Podicherry,Place_Pune,Company_CTS,Company_Congnizant,Company_Infosys,Company_Infosys Pvt Lmt,Company_TCS,Company_Tata Consultancy Services,Country_India
0,20.0,NaN,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,1
1,30.0,NaN,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
2,35.0,2300.0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
3,40.0,3000.0,1,0,0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,1
4,23.0,4000.0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1

The data types are checked again to verify that the categorical columns have been converted into numerical form.

In [44]:
df.dtypes

Age                                  float64
Salary                               float64
Gender_0                               int64
Gender_1                               int64
Place_Bhopal                           int64
Place_Calcutta                         int64
Place_Chennai                          int64
Place_Cochin                           int64
Place_Delhi                            int64
Place_Hyderabad                        int64
Place_Mumbai                           int64
Place_Nagpur                           int64
Place_Noida                            int64
Place_Podicherry                       int64
Place_Pune                             int64
Company_CTS                            int64
Company_Congnizant                     int64
Company_Infosys                        int64
Company_Infosys Pvt Lmt                int64
Company_TCS                            int64
Company_Tata Consultancy Services      int64
Country_India                          int64
dtype: object

### Step 9: Feature Scaling

Standardization changes the numerical features so that they have a mean of approximately 0 and a standard deviation of approximately 1.

In [45]:
from sklearn.preprocessing import StandardScaler

A StandardScaler object is created to perform standardization on the numerical data.

In [46]:
scaler = StandardScaler()

The scaler is fitted to the dataset and the numerical values are transformed into standardized values.

In [47]:
df_standardized = scaler.fit_transform(df)

df_standardized

array([[-0.95092413,         nan,  0.53452248, ...,  1.33012434,
        -0.11867817,  0.        ],
       [-0.04765289,         nan,  0.53452248, ..., -0.75180941,
        -0.11867817,  0.        ],
       [ 0.40398273, -1.15877891,  0.53452248, ...,  1.33012434,
        -0.11867817,  0.        ],
       ...,
       [ 1.21692684, -0.48529404, -1.87082869, ..., -0.75180941,
        -0.11867817,  0.        ],
       [ 0.22332848, -0.09689446, -1.87082869, ...,  1.33012434,
        -0.11867817,  0.        ],
       [-0.77026988,  1.13355541,  0.53452248, ..., -0.75180941,
        -0.11867817,  0.        ]], shape=(144, 22))

The standardized NumPy array is converted back into a Pandas DataFrame so that the data can be easily viewed and analyzed.

In [48]:
df_standardized = pd.DataFrame(
    df_standardized,
    columns=df.columns
)

df_standardized.head()

,Age,Salary,Gender_0,Gender_1,Place_Bhopal,Place_Calcutta,Place_Chennai,Place_Cochin,Place_Delhi,Place_Hyderabad,...,Place_Noida,Place_Podicherry,Place_Pune,Company_CTS,Company_Congnizant,Company_Infosys,Company_Infosys Pvt Lmt,Company_TCS,Company_Tata Consultancy Services,Country_India
0,-0.950924,NaN,0.534522,-0.534522,-0.083624,-0.534522,3.047247,-0.315018,-0.328165,-0.242536,...,-0.242536,-0.145865,-0.118678,-0.566658,-0.118678,-0.652490,-0.118678,1.330124,-0.118678,0.0
1,-0.047653,NaN,0.534522,-0.534522,-0.083624,-0.534522,-0.328165,-0.315018,-0.328165,-0.242536,...,-0.242536,-0.145865,-0.118678,-0.566658,-0.118678,1.532592,-0.118678,-0.751809,-0.118678,0.0
2,0.403983,-1.158779,0.534522,-0.534522,-0.083624,1.870829,-0.328165,-0.315018,-0.328165,-0.242536,...,-0.242536,-0.145865,-0.118678,-0.566658,-0.118678,-0.652490,-0.118678,1.330124,-0.118678,0.0
3,0.855618,-0.886899,0.534522,-0.534522,-0.083624,-0.534522,-0.328165,-0.315018,3.047247,-0.242536,...,-0.242536,-0.145865,-0.118678,-0.566658,-0.118678,1.532592,-0.118678,-0.751809,-0.118678,0.0
4,-0.679943,-0.498500,0.534522,-0.534522,-0.083624,-0.534522,-0.328165,-0.315018,-0.328165,-0.242536,...,-0.242536,-0.145865,-0.118678,-0.566658,-0.118678,-0.652490,-0.118678,1.330124,-0.118678,0.0

### Step 10: Min-Max Normalization

Min-Max normalization transforms the values into a fixed range, usually between 0 and 1.

In [49]:
from sklearn.preprocessing import MinMaxScaler

A MinMaxScaler object is created to normalize the dataset.

In [50]:
minmax_scaler = MinMaxScaler()

The MinMaxScaler is fitted to the dataset and transforms the values into the range from 0 to 1.

In [51]:
df_normalized = minmax_scaler.fit_transform(df)

df_normalized

array([[0.37037037,        nan, 1.        , ..., 1.        , 0.        ,
        0.        ],
       [0.55555556,        nan, 1.        , ..., 0.        , 0.        ,
        0.        ],
       [0.64814815, 0.13781723, 1.        , ..., 1.        , 0.        ,
        0.        ],
       ...,
       [0.81481481, 0.33515421, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.61111111, 0.44895869, 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.40740741, 0.80949129, 1.        , ..., 0.        , 0.        ,
        0.        ]], shape=(144, 22))

The normalized data is converted into a Pandas DataFrame for easier viewing.

In [52]:
df_normalized = pd.DataFrame(
    df_normalized,
    columns=df.columns
)

df_normalized.head()

,Age,Salary,Gender_0,Gender_1,Place_Bhopal,Place_Calcutta,Place_Chennai,Place_Cochin,Place_Delhi,Place_Hyderabad,...,Place_Noida,Place_Podicherry,Place_Pune,Company_CTS,Company_Congnizant,Company_Infosys,Company_Infosys Pvt Lmt,Company_TCS,Company_Tata Consultancy Services,Country_India
0,0.370370,NaN,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,0.555556,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,0.648148,0.137817,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.740741,0.217480,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0.425926,0.331285,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

The final shape and first few rows of the pre-processed dataset are displayed to verify that the preprocessing was completed successfully.

In [53]:
print("Final Dataset Shape:", df.shape)

df.head()

Final Dataset Shape: (144, 22)

,Age,Salary,Gender_0,Gender_1,Place_Bhopal,Place_Calcutta,Place_Chennai,Place_Cochin,Place_Delhi,Place_Hyderabad,...,Place_Noida,Place_Podicherry,Place_Pune,Company_CTS,Company_Congnizant,Company_Infosys,Company_Infosys Pvt Lmt,Company_TCS,Company_Tata Consultancy Services,Country_India
0,20.0,NaN,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,1
1,30.0,NaN,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
2,35.0,2300.0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
3,40.0,3000.0,1,0,0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,1
4,23.0,4000.0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1

### Final Verification

We check the pre-processed dataset to make sure that the missing values have been handled successfully.

In [54]:
df.isnull().sum()

Age                                  17
Salary                               23
Gender_0                              0
Gender_1                              0
Place_Bhopal                          0
Place_Calcutta                        0
Place_Chennai                         0
Place_Cochin                          0
Place_Delhi                           0
Place_Hyderabad                       0
Place_Mumbai                          0
Place_Nagpur                          0
Place_Noida                           0
Place_Podicherry                      0
Place_Pune                            0
Company_CTS                           0
Company_Congnizant                    0
Company_Infosys                       0
Company_Infosys Pvt Lmt               0
Company_TCS                           0
Company_Tata Consultancy Services     0
Country_India                         0
dtype: int64

The data types are checked to confirm that the categorical variables have been converted into numerical form.

In [55]:
df.dtypes

Age                                  float64
Salary                               float64
Gender_0                               int64
Gender_1                               int64
Place_Bhopal                           int64
Place_Calcutta                         int64
Place_Chennai                          int64
Place_Cochin                           int64
Place_Delhi                            int64
Place_Hyderabad                        int64
Place_Mumbai                           int64
Place_Nagpur                           int64
Place_Noida                            int64
Place_Podicherry                       int64
Place_Pune                             int64
Company_CTS                            int64
Company_Congnizant                     int64
Company_Infosys                        int64
Company_Infosys Pvt Lmt                int64
Company_TCS                            int64
Company_Tata Consultancy Services      int64
Country_India                          int64
dtype: object

## Conclusion

In this experiment, data pre-processing was successfully performed on the Employee dataset. Duplicate records were identified and removed, inconsistent values were corrected, missing values were handled, and categorical variables were converted into numerical form. Standardization and Min-Max normalization were also applied to prepare the dataset for further machine learning analysis.